export interface Exercise {
  id: string
  category: string
  question: string
  options: string[]
  correct: number
  explanation: string
  fen?: string
}

export const exercises: Exercise[] = [
  {
    id: 'p-01',
    category: 'pieces',
    question: 'Qual é o valor da Dama em pontos?',
    options: ['3', '5', '9', '1'],
    correct: 2,
    explanation: 'A Dama vale 9 pontos. É a peça mais poderosa do tabuleiro, combinando os movimentos da Torre e do Bispo.',
  },
  {
    id: 'p-02',
    category: 'pieces',
    question: 'Quantas peças cada jogador tem no início da partida?',
    options: ['12', '16', '8', '20'],
    correct: 1,
    explanation: 'Cada jogador começa com 16 peças: 1 Rei, 1 Dama, 2 Torres, 2 Bispos, 2 Cavalos e 8 Peões.',
  },
  {
    id: 'p-03',
    category: 'pieces',
    question: 'Qual peça vale menos pontos individualmente?',
    options: ['Cavalo', 'Bispo', 'Torre', 'Peão'],
    correct: 3,
    explanation: 'O Peão vale apenas 1 ponto. Mas apesar de ser a peça de menor valor, os Peões são fundamentais para controlar o centro do tabuleiro.',
  },
  {
    id: 'p-04',
    category: 'pieces',
    question: 'Qual peça NÃO pode pular sobre outras peças?',
    options: ['Cavalo', 'Torre', 'Ambos podem pular', 'Nenhum pode pular'],
    correct: 1,
    explanation: 'Apenas o Cavalo pode pular sobre outras peças. A Torre, assim como as demais peças (exceto o Cavalo), precisa do caminho livre.',
  },
  {
    id: 'p-05',
    category: 'pieces',
    question: 'Qual peça é a mais importante do jogo (sem ela, você perde)?',
    options: ['Dama', 'Torre', 'Rei', 'Peão'],
    correct: 2,
    explanation: 'O Rei é a peça mais importante. Se o Rei for capturado (xeque-mate), o jogo acaba. O Rei não tem valor em pontos — ele é inestimável.',
  },
  {
    id: 'm-01',
    category: 'moves',
    question: 'Como o Cavalo se move?',
    options: ['Em linha reta', 'Na diagonal', 'Em "L" (2+1 casas)', 'Uma casa em qualquer direção'],
    correct: 2,
    explanation: 'O Cavalo se move em forma de "L": duas casas em uma direção e uma casa perpendicular. É o único movimento que não é em linha reta.',
  },
  {
    id: 'm-02',
    category: 'moves',
    question: 'Quantas direções o Rei pode se mover?',
    options: ['4 (horizontal/vertical)', '4 (diagonais)', '8 (todas as direções)', '2 (frente/trás)'],
    correct: 2,
    explanation: 'O Rei pode se mover uma casa em qualquer direção: horizontal, vertical e diagonal — totalizando 8 direções possíveis.',
  },
  {
    id: 'm-03',
    category: 'moves',
    question: 'No primeiro movimento, o Peão pode avançar quantas casas?',
    options: ['Sempre 1', '1 ou 2 (à escolha)', 'Sempre 2', '1, 2 ou 3'],
    correct: 1,
    explanation: 'No seu primeiro movimento, o Peão pode avançar uma ou duas casas para frente. Após o primeiro movimento, só pode avançar uma casa por vez.',
  },
  {
    id: 'm-04',
    category: 'moves',
    question: 'A Dama pode se mover como a combinação de quais peças?',
    options: ['Torre e Cavalo', 'Torre e Bispo', 'Bispo e Cavalo', 'Rei e Torre'],
    correct: 1,
    explanation: 'A Dama combina os movimentos da Torre (horizontal e vertical) com os do Bispo (diagonais). É a peça mais versátil.',
  },
  {
    id: 'm-05',
    category: 'moves',
    question: 'Qual direção o Peão captura outras peças?',
    options: ['Para frente (reto)', 'Na diagonal para frente', 'Para trás', 'Em qualquer direção'],
    correct: 1,
    explanation: 'O Peão é a única peça que captura diferente de como se move: ele avança reto, mas captura na diagonal (uma casa para frente na diagonal).',
  },
  {
    id: 'c-01',
    category: 'captures',
    question: 'Se você trocar seu Bispo (3 pts) por uma Torre inimiga (5 pts), isso é:',
    options: ['Uma troca ruim', 'Uma troca igual', 'Uma troca vantajosa', 'Proibido'],
    correct: 2,
    explanation: 'Isso é uma troca vantajosa! Você ganha 5 pontos e perde apenas 3, ficando com 2 pontos de vantagem material.',
  },
  {
    id: 'c-02',
    category: 'captures',
    question: 'O que é "En Passant"?',
    options: [
      'Um tipo de xeque-mate',
      'Uma captura especial de Peão',
      'Um movimento do Rei',
      'Uma abertura de jogo',
    ],
    correct: 1,
    explanation: 'En Passant ("de passagem") é uma captura especial de Peão. Quando um Peão avança duas casas e para ao lado de um Peão adversário, este pode capturá-lo como se tivesse andado apenas uma casa.',
  },
  {
    id: 'c-03',
    category: 'captures',
    question: 'Qual peça é boa para capturar Peões no final do jogo?',
    options: ['Cavalo', 'Bispo', 'Torre', 'Rei'],
    correct: 2,
    explanation: 'A Torre é excelente no final do jogo porque controla fileiras inteiras e pode capturar Peões que tentam avançar para a promoção.',
  },
  {
    id: 'c-04',
    category: 'captures',
    question: 'Se uma Dama (9 pts) captura um Cavalo protegido (3 pts), mas é capturada na sequência:',
    options: ['Bom negócio', 'Mau negócio', 'Troca igual', 'Não é permitido'],
    correct: 1,
    explanation: 'É um mau negócio! Você perde 9 pontos e ganha apenas 3 — um prejuízo de 6 pontos. Sempre verifique se a peça inimiga está protegida antes de capturá-la.',
  },
  {
    id: 'ch-01',
    category: 'check',
    question: 'Se seu Rei está em xeque, quantas opções você tem para sair?',
    options: ['1', '2', '3', 'Nenhuma — você perdeu'],
    correct: 2,
    explanation: 'Existem 3 maneiras de sair de um xeque: 1) Mover o Rei para uma casa segura, 2) Bloquear o ataque com outra peça, 3) Capturar a peça que está dando xeque.',
  },
  {
    id: 'ch-02',
    category: 'check',
    question: 'Qual destas situações é xeque?',
    options: [
      'Sua Dama pode capturar o Rei inimigo no próximo lance',
      'Seu Rei não pode se mover (todas as casas estão atacadas)',
      'Sua Torre está alinhada com o Rei adversário sem peças no meio',
      'Você perdeu uma peça',
    ],
    correct: 2,
    explanation: 'Xeque acontece quando uma peça sua está atacando o Rei adversário. Se sua Torre está alinhada com o Rei inimigo sem peças bloqueando, o Rei está em xeque.',
  },
  {
    id: 'ch-03',
    category: 'check',
    question: 'Você pode se mover para uma casa que coloca seu próprio Rei em xeque?',
    options: ['Sim', 'Não', 'Sim, mas só com o Peão', 'Sim, mas só uma vez por jogo'],
    correct: 1,
    explanation: 'Não! É proibido fazer um lance que coloque seu próprio Rei em xeque. Isso é chamado de "lance ilegal".',
  },
  {
    id: 'cm-01',
    category: 'checkmate',
    question: 'O que é xeque-mate?',
    options: [
      'Quando o Rei está em xeque',
      'Quando não há mais peças no tabuleiro',
      'Xeque sem possibilidade de escapar',
      'Capturar a Dama adversária',
    ],
    correct: 2,
    explanation: 'Xeque-mate é quando o Rei está em xeque e não há como escapar: não pode se mover, não pode bloquear e não pode capturar a peça atacante. É o fim do jogo.',
  },
  {
    id: 'cm-02',
    category: 'checkmate',
    question: 'Com quais peças é possível dar xeque-mate em um Rei solitário?',
    options: ['Apenas Dama', 'Dama ou Torre (com Rei)', 'Qualquer peça sozinha', 'Apenas com 2 Cavalos'],
    correct: 1,
    explanation: 'Com o auxílio do seu Rei, você pode dar xeque-mate usando uma Dama ou uma Torre. Dois Bispos também funcionam. Um Cavalo sozinho não consegue dar mate.',
  },
  {
    id: 'cm-03',
    category: 'checkmate',
    question: 'Qual é o xeque-mate mais rápido possível (Mate do Louco)?',
    options: ['1 lance', '2 lances', '4 lances', 'Não é possível dar mate tão rápido'],
    correct: 1,
    explanation: 'O Mate do Louco acontece em apenas 2 lances! 1.f3 e5 2.g4 Dh4#. É por isso que mover os Peões f e g no início é perigoso.',
  },
  {
    id: 'cm-04',
    category: 'checkmate',
    question: 'Qual abertura pode levar ao Mate do Pastor (4 lances)?',
    options: ['1.e4 e5 2.Bc4 Cc6 3.Dh5 Cf6?? 4.Dxf7#', '1.d4 d5 2.c4', '1.Cf3 Cf6 2.g3', '1.e4 c5'],
    correct: 0,
    explanation: 'O Mate do Pastor é uma armadilha comum para iniciantes! Após 1.e4 e5 2.Bc4 Cc6 3.Dh5, se as pretas jogarem Cf6?? (erro!), segue 4.Dxf7#. Sempre proteja o peão f7/f2!',
  },
  {
    id: 'misc-01',
    category: 'moves',
    question: 'Para que lado o tabuleiro deve ser posicionado?',
    options: [
      'Casa branca na direita de cada jogador',
      'Casa preta na direita de cada jogador',
      'Tanto faz',
      'Depende de quem joga de brancas',
    ],
    correct: 0,
    explanation: 'O tabuleiro sempre deve ser posicionado com uma casa branca (ou clara) no canto direito de cada jogador. Lembre-se: "Branca na direita".',
  },
]
